# Set theme
#remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
#url: 'https://julienjuan.com'
baseurl: ''
title: 'Julien Juan'
#description: 'This is my new website'
permalink: pretty
#logo: "/assets/logo.jpg"
logo: "/blog/assets/Julien-Juan-9740.jpg"
# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Articles
  url: /
- title: A propos
  url: /blog/about/
- title: Contact
  url: /blog/contact/

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "My thoughts and ideas"
    feature_text: |
      Welcome to my blog
    feature_image: "/blog/assets/logo/jpg"
